Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2018-04, with the labels that each got.

#207 Fix graphviz link
  README.md
Labels: Documentation

#209 Remove doxygen link bugs (resolves #206 )
  doxygen_config.cmake.in
  osi_common.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
  osi_detectedroadmarking.proto
  osi_detectedtrafficlight.proto
  osi_detectedtrafficsign.proto
  osi_featuredata.proto
  osi_lane.proto
  osi_object.proto
  osi_sensordata.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  osi_trafficsign.proto
Labels: Documentation, bug

#211 update readme
  README.md
Labels: Documentation

#212 Remove warnings
  .gitignore
  doxygen_config.cmake.in
  osi_object.proto
  osi_sensordata.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
Labels: Documentation

#204 Correct cmake version check and install
  CMakeLists.txt
  VERSION
  open_simulation_interface-config-version.cmake.in
Labels: bug, enhancement

#213 Update Documentation (resolves #210)
  osi_common.proto
  osi_detectedobject.proto
  osi_environment.proto
  osi_featuredata.proto
  osi_groundtruth.proto
  osi_lane.proto
  osi_object.proto
  osi_sensordata.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
Labels: Documentation

#215 Small changes
  README.md
  osi_lane.proto
  osi_roadmarking.proto
  osi_trafficlight.proto
  osi_trafficsign.proto
Labels: Documentation

#217 OSI V3 correct cmake version check and install
  CMakeLists.txt
  open_simulation_interface-config-version.cmake.in
Labels: bug, enhancement

#214 Documenation/GitHub pages
  .travis.yml
  VERSION
Labels: Documentation, enhancement

#216 Update readme.md
  README.md
  osi_object.proto
  osi_sensorviewconfiguration.proto
  test_cases.py
Labels: Documentation

#224 Documentation/v3.0.1 update 7
  .travis.yml
  README.md
  doxygen_config.cmake.in
  open_simulation_interface-config-version.cmake.in
  osi_common.proto
  osi_detectedlane.proto
  osi_featuredata.proto
  osi_roadmarking.proto
  osi_sensordata.proto
  osi_version.proto.in
  test_cases.py
  test_cases_doc.py
Labels: Documentation, quality

#226 Extend documentation for traffic sign exit poles (resolves #220)
  osi_trafficsign.proto
Labels: Documentation
