Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2018-12, with the labels that each got.

#293 First proposal for US Sensors
  doc/images/OSI_DetectedTrafficLight.svg
  doc/images/OSI_USSensor.svg
  doc/images/OSI_USSensor_direct.svg
  doc/images/OSI_USSensor_indirect.svg
  osi_featuredata.proto
  osi_sensorspecific.proto
Labels: enhancement

#277 Add relative path of map in GroundTruth fixes #278
  osi_groundtruth.proto
Labels: Suggestions, enhancement

#297 Added Emergency and Service vehicle illumination.
  osi_object.proto
Labels: enhancement

#291 Added orientation acceleration to message BaseMoving (solves #279)
  osi_common.proto
Labels: enhancement

#298 Camera detecions
  doxygen_config.cmake.in
  osi_featuredata.proto
Labels: enhancement

#299 Documentation3.1.0 v001
  doxygen_config.cmake.in
  osi_common.proto
  osi_detectedobject.proto
  osi_groundtruth.proto
  osi_lane.proto
  osi_object.proto
  osi_trafficsign.proto
  osi_version.proto.in
  test_cases.py
Labels: Documentation
