Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2018-03, with the labels that each got.

#150 Define BaseStationary orientation for OSI::Landmarks
  osi_landmark.proto
Labels: enhancement

#124 Improvements on extended traffic signs
  osi_landmark.proto
Labels: enhancement, help wanted

#158 Use vehicle axis system definition of DIN ISO 8855
  osi_common.proto
  osi_detectedobject.proto
  osi_featuredata.proto
  osi_landmark.proto
  osi_object.proto
  osi_sensordata.proto
  osi_sensorinputconfiguration.proto
  osi_sensorspecific.proto
Labels: Documentation

#159 Reformatting and review
  osi_environment.proto
  osi_groundtruth.proto
  osi_hostvehicledata.proto
  osi_landmark.proto
  osi_lane.proto
  osi_occupant.proto
Labels: Documentation

#162 Review documentation (issue #97)
  osi_common.proto
  osi_datarecording.proto
  osi_detectedobject.proto
  osi_featuredata.proto
  osi_landmark.proto
  osi_lane.proto
  osi_object.proto
  osi_sensordata.proto
  osi_sensorspecific.proto
  osi_sensorview.proto
Labels: Documentation

#161 New proposal for SensorID List
  osi_detectedlandmark.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
  osi_featuredata.proto
  osi_sensordata.proto
Labels: Documentation, enhancement

#160 Replacing semantic Traffic Lights with Traffic Light Bulbs (issue #70)
  osi_detectedlandmark.proto
  osi_landmark.proto
Labels: enhancement

#170 Landmarks added (issue #166)
  osi_detectedlandmark.proto
  osi_groundtruth.proto
  osi_landmark.proto
  osi_sensordata.proto
Labels: enhancement

#180 Add relative humidity to environment data
  osi_environment.proto
Labels: enhancement

#179 Seperate SensorView from SensorData
  CMakeLists.txt
  osi_sensordata.proto
  osi_sensorinputconfiguration.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  setup.py
Labels: enhancement

#182 Allow repeated SensorView copies in SensorData
  osi_sensordata.proto
Labels: enhancement

#167 Review documentation and add BaseStationary to supplementary signs
  osi_common.proto
  osi_datarecording.proto
  osi_detectedlandmark.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
  osi_environment.proto
  osi_featuredata.proto
  osi_groundtruth.proto
  osi_hostvehicledata.proto
  osi_landmark.proto
  osi_lane.proto
  osi_modelinternal.proto
  osi_object.proto
  osi_occupant.proto
  osi_sensordata.proto
  osi_sensorspecific.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
Labels: Documentation

#184 Extend definition of vehicles
  osi_object.proto
Labels: enhancement

#183 Feature/cmake install
  .travis.yml
  CMakeLists.txt
  VERSION
  osi_common.proto
  osi_datarecording.proto
  osi_detectedlandmark.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
  osi_environment.proto
  osi_featuredata.proto
  osi_groundtruth.proto
  osi_hostvehicledata.proto
  osi_landmark.proto
  osi_lane.proto
  osi_modelinternal.proto
  osi_object.proto
  osi_occupant.proto
  osi_sensordata.proto
  osi_sensorspecific.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  osi_version.proto.in
  setup.py
Labels: enhancement

#188 Maintenance/v2.2.x fixes
  .travis.yml
  CMakeLists.txt
Labels: bug

#168 Remove RelevantLane and RelevantDirection in Detected...
  osi_detectedlandmark.proto
  osi_landmark.proto
Labels: Suggestions, duplicate

#193 Update/traffic sign value message
  osi_landmark.proto
Labels: enhancement

#194 Generic Sensor Sub Views and Timestamps
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
Labels: enhancement

#186 DetectedLane similar to other detected messages.
  osi_detectedlane.proto
Labels: enhancement

#176 Replace Landmark messages with StationaryObject messages
  osi_detectedobject.proto
  osi_groundtruth.proto
  osi_object.proto
  osi_sensordata.proto
Labels: Suggestions

#195 Update documentation
  osi_common.proto
Labels: Documentation

#196 Restructuring DetectedXXX messages
  osi_detectedlandmark.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
Labels: enhancement

#201 Update osi_object.proto
  osi_object.proto
Labels: Documentation

#200 Improvement/harmonize detectedobjects (solves #197)
  CMakeLists.txt
  README.md
  doxygen_config.cmake.in
  osi_common.proto
  osi_datarecording.proto
  osi_detectedlandmark.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
  osi_featuredata.proto
  osi_groundtruth.proto
  osi_landmark.proto
  osi_lane.proto
  osi_modelinternal.proto
  osi_object.proto
  osi_occupant.proto
  osi_sensordata.proto
  osi_sensorspecific.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  osi_version.proto.in
  setup.py
  test_cases.py
Labels: Documentation, enhancement, help wanted
