Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2020-02, with the labels that each got.

#371 WIP:Documentation/citation style
  README.md
  doc/commenting.rst
  osi_common.proto
  osi_detectedobject.proto
  osi_environment.proto
  osi_featuredata.proto
  osi_groundtruth.proto
  osi_lane.proto
  osi_object.proto
  osi_sensordata.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  osi_version.proto.in
Labels: documentation

#374 Fix message offset
  format/OSITrace.py
  format/osi2read.py
  format/txt2osi.py
Labels: bug, quality

#375 Unit test for rules
  doc/commenting.rst
  rules.yml
  tests/test_rules.py
Labels: quality

#376 File naming
  doc/fileformat.rst
Labels: documentation

#378 Resolves issue #306
  osi_featuredata.proto
Labels: bug, documentation

#379 Reserve fields above 10000 for extensions (#346)
  doc/description.rst
Labels: feature request

#380 Documentation/interface convention
  doc/commenting.rst
  doc/interfaceconventions.rst
Labels: documentation, quality

#381 Update release names
  doc/releases.rst
Labels: documentation, quality

#382 Release documentation:
  doc/releases/v02.00.rst
  doc/releases/v02.01.rst
  doc/releases/v02.02.rst
  doc/releases/v03.00.rst
  doc/releases/v03.01.rst
  doc/releases/v03.02.rst
Labels: documentation
