Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-01, with the labels that each got.

#461 Make exclusion of side mirrors for vehicle bounding boxes clearer
  doc/images/OSI_BaseMoving.svg
  doc/images/OSI_BaseMoving_Top.svg
  osi_common.proto
  osi_object.proto
Labels: Harmonisation, ReadyToMerge

#460 Point order of centerline and lane bounaries
  doc/images/OSI_LaneBoundaries_And_CenterLine.svg
  osi_lane.proto
Labels: Harmonisation, ReadyToMerge

#453 Add some new Actions in OSI::TrafficCommand
  osi_trafficcommand.proto
Labels: FeatureRequest, ReadyToMerge, TrafficParticipants

#431 Add lane sub-types to represent OpenDRIVE lane type information
  osi_lane.proto
Labels: FeatureRequest, Harmonisation, ReadyToMerge

#430 Extension by wheel data
  doc/images/OSI_RotationRate.svg
  osi_object.proto
Labels: FeatureRequest, ReadyToMerge, SensorModeling, TrafficParticipants
