Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-05, with the labels that each got.

#514 Migration of build pipeline to GitHub actions
  .github/workflows/protobuf.yml
  .travis.yml
  README.md
Labels: ReadyToMerge

#505 Harmonization of road mark colors with OpenDRIVE
  osi_lane.proto
  osi_roadmarking.proto
Labels: Documentation, Harmonisation, ReadyToMerge

#497 Avoid duplication of pylons in enum
  osi_object.proto
Labels: Bug, ReadyToMerge, SensorModeling
