Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-06, with the labels that each got.

#519 Describe installation under Linux and Windows
  doc/open-simulation-interface_user_guide.adoc
  doc/setup/installing_linux.adoc
  doc/setup/installing_linux_cpp.adoc
  doc/setup/installing_linux_python.adoc
  doc/setup/installing_windows.adoc
  doc/setup/installing_windows_cpp.adoc
  doc/setup/installing_windows_python.adoc
Labels: Documentation, ReadyToMerge

#465 Definiton of external references
  osi_common.proto
  osi_environment.proto
  osi_lane.proto
  osi_object.proto
  osi_occupant.proto
  osi_roadmarking.proto
  osi_trafficlight.proto
  osi_trafficsign.proto
Labels: Documentation, FeatureRequest, Harmonisation, ReadyToMerge

#483 Feature/tp/add speed bumps #448
  osi_object.proto
Labels: FeatureRequest, ReadyToMerge, TrafficParticipants
