Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-02, with the labels that each got.

#466 set default c11 compiler for apple machines
  CMakeLists.txt
Labels: Bug, ReadyToMerge

#440 Add new LogicalDetectionData message to SensorData
  CMakeLists.txt
  doc/osifiles.rst
  osi_logicaldetectiondata.proto
  osi_sensordata.proto
  setup.py
Labels: FeatureRequest, ReadyToMerge, SensorModeling

#474 Make handling of enums in rules check more robust
  tests/test_rules.py
Labels: Bug, ReadyToMerge

#479 Add steering wheel angle
  osi_object.proto
Labels: ReadyToMerge, WP7 - Visualization

#473 Reworked Checklist for each PR
  .github/pull_request_template.md
Labels: Quality, ReadyToMerge

#446 Updated CameraSensorViewConfiguration Message
  .gitignore
  osi_common.proto
  osi_sensorviewconfiguration.proto
Labels: FeatureRequest, ReadyToMerge, SensorModeling

#477 Moved different action definitions into message trafficAction.
  osi_trafficcommand.proto
Labels: Quality, ReadyToMerge

#470 Documentation/ground clearance bb relation
  osi_detectedobject.proto
  osi_object.proto
Labels: Quality, ReadyToMerge

#368 Move assigned_lane_id in osi_object.proto to VehicleClassification
  osi_detectedobject.proto
  osi_object.proto
Labels: Bug, ReadyToMerge, TrafficParticipants

#485 Readme update for generating a scenario
  README.md
Labels: ReadyForCCBReview
