Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-03, with the labels that each got.

#487 Added release notes for 3.3.0
  doc/releases.rst
  doc/releases/v03.03.rst
Labels: Documentation, ReadyForCCBReview

#493 Correct typos in model_reference comments in osi_groundtruth.proto
  osi_groundtruth.proto
Labels: Documentation, ReadyToMerge

#503 494 set up initial document structure
  doc/architecture/architecture_overview.adoc
  doc/architecture/coordinate_systems.adoc
  doc/architecture/data_layer.adoc
  doc/architecture/environmental_effect_model.adoc
  doc/architecture/feature_data.adoc
  doc/architecture/formatting_scripts.adoc
  doc/architecture/ground_truth.adoc
  doc/architecture/logical_model.adoc
  doc/architecture/packaging_layer.adoc
  doc/architecture/proto-files.adoc
  doc/architecture/reference_points.adoc
  doc/architecture/sensor_data.adoc
  doc/architecture/sensor_model.adoc
  doc/architecture/sensor_view.adoc
  doc/architecture/sensor_view_configuration.adoc
  doc/architecture/test_scripts.adoc
  doc/architecture/trace_file_formats.adoc
  doc/architecture/trace_file_naming.adoc
  doc/architecture/traffic_participant.adoc
  doc/architecture/vehicle_dynamics.adoc
  doc/commenting.rst
  doc/coordinatesystem.rst
  doc/description.rst
  doc/fileformat.rst
  doc/howtocontribute.rst
  doc/installation.rst
  doc/interfaceconventions.rst
  doc/linux.rst
  doc/misc/osi_reference.adoc
  doc/misc/osi_vision.adoc
  doc/open-simulation-interface_user_guide.adoc
  doc/osifiles.rst
  doc/reference.rst
  doc/releases.rst
  doc/releases/compatibility.adoc
  doc/releases/releases.adoc
  doc/releases/versioning.adoc
  doc/setup/including_osi_dev_projects.adoc
  doc/setup/installing_linux.adoc
  doc/setup/installing_macos.adoc
  doc/setup/installing_windows.adoc
  doc/setup/using_osi_support_tools.adoc
  doc/usecases/benchmark_integration_gpu_radar.adoc
  doc/usecases/fusing_sensor_outputs.adoc
  doc/usecases/generating_osi_traces.adoc
  doc/usecases/injecting_faults.adoc
  doc/usecases/modeling_camera_electronics.adoc
  doc/usecases/modeling_lidar_sensor.adoc
  doc/usecases/modeling_traffic_participant.adoc
  doc/versioning.rst
  doc/windows.rst
Labels: Documentation
