Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-07, with the labels that each got.

#536 feat(docs): Add link to reference documentation (#531)
  doc/misc/osi_reference.adoc
Labels: Documentation, ReadyForCCBReview

#541 Add vision topic
  doc/misc/osi_vision.adoc
Labels: Documentation, ReadyToMerge

#482 Extension for Traffic Sign classification for better harmonisation with OpenDRIVE
  osi_roadmarking.proto
  osi_trafficsign.proto
Labels: Documentation, Harmonisation, ReadyToMerge

#472 Introducing emitting objects
  osi_common.proto
  osi_object.proto
Labels: ReadyToMerge, SensorModeling
