Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2021-09, with the labels that each got.

#523 Align custom traffic action with osc
  osi_trafficcommand.proto
Labels: Bug, Documentation, TrafficParticipants, ReadyToMerge

#554 Introducing new color models
  osi_common.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedroadmarking.proto
  osi_detectedtrafficlight.proto
  osi_featuredata.proto
  osi_lane.proto
  osi_object.proto
  osi_roadmarking.proto
  osi_trafficlight.proto
Labels: Documentation, Harmonisation, ReadyToMerge

#491 add StationaryObjectClassification including assigned_lane_id and ass…
  osi_object.proto
Labels: FeatureRequest, Documentation, TrafficParticipants, ReadyToMerge

#567 Add dash property to boundary points
  osi_lane.proto
Labels: Documentation, Harmonisation
