Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2022-05, with the labels that each got.

#607 Added coordinate transformation to documentation
  doc/architecture/reference_points_coordinate_systems.adoc
  doc/usecases/transforming_coordinate_systems.adoc
Labels: Documentation, ReadyToMerge

#610 Docu/remove note on singular plural
  doc/architecture/architecture_overview.adoc
  osi_datarecording.proto
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedoccupant.proto
  osi_detectedroadmarking.proto
  osi_detectedtrafficlight.proto
  osi_detectedtrafficsign.proto
  osi_featuredata.proto
  osi_groundtruth.proto
  osi_logicaldetectiondata.proto
  osi_object.proto
  osi_sensordata.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  osi_trafficsign.proto
Labels: Documentation, ReadyToMerge

#593 Environmental conditions, added Sun, Wind, CloudState
  osi_environment.proto
Labels: Documentation, Harmonisation, ReadyToMerge

#615 Traffic Command Update
  osi_trafficcommand.proto
  osi_trafficcommandupdate.proto
Labels: TrafficParticipants, ReadyToMerge

#631 Correct documentation of Identifier of ReferenceLine
  osi_referenceline.proto
Labels: ReadyToMerge, RoadModel4.0

#624 Introducing Operating States
  osi_hostvehicledata.proto
Labels: FeatureRequest, ReadyToMerge

#551 #550 cmake build is missing key features to be properly usable via fetchcontent
  .gitignore
  CMakeLists.txt
  open_simulation_interface-config.cmake.in
Labels: ReadyToMerge

#633 Extending Wheel Data by Friction Coefficient
  osi_object.proto
Labels: ReadyToMerge

#613 Add Role to VehicleClassification
  osi_object.proto
Labels: Harmonisation, ReadyToMerge

#634 Concretize lane boundary modelling for lanes at different heights
  osi_lane.proto
Labels: ReadyToMerge, RoadModel4.0
