Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2022-12, with the labels that each got.

#696 Fixing title of Fig. 10 with coordinate systems
  doc/usecases/transforming_coordinate_systems.adoc
Labels: Documentation, ReadyToMerge

#683 Add new traffic sign variability types
  osi_trafficsign.proto
Labels: SensorModeling, Harmonisation, ReadyToMerge

#676 Add new enum Type in vehicle classification for stand-up scooters
  osi_object.proto
Labels: FeatureRequest, ReadyToMerge

#651 Adapt ReferenceLine ST definition to avoid transformation ambiguity and discontinuities
  doc/images/OSI_ReferenceLine2.svg
  osi_referenceline.proto
Labels: Harmonisation, ReadyToMerge, Other Models
