Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2022-02, with the labels that each got.

#589 Add automated driving function state to host vehicle data
  osi_common.proto
  osi_hostvehicledata.proto
  osi_trafficupdate.proto
Labels: FeatureRequest, Documentation, ReadyToMerge

#617 Dependebility: Bumb protobuf version
  README.md
Labels: Analysis, ReadyToMerge

#616 Tweak Doxygen output
  doxygen_config.cmake.in
Labels: ReadyToMerge
