Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2023-03, with the labels that each got.

#590 Adding the missing field for echo pulse width to logical detections
  osi_logicaldetectiondata.proto
Labels: FeatureRequest, ReadyToMerge, OpenMSL

#701 Logical lanes: add street name
  osi_logicallane.proto
Labels: Harmonisation, ReadyToMerge, Other Models

#452 Feature/tp/had output
  .gitignore
  CMakeLists.txt
  doc/_config.adoc
  doc/architecture/architecture_overview.adoc
  doc/architecture/motion_request.adoc
  doc/architecture/traffic_participant.adoc
  doc/images/osi-traffic-participant-advanced.png
  doc/images/osi-traffic-participant-principle.png
  doc/images/osi-traffic-participant-use-case-1.png
  doc/images/osi-traffic-participant-use-case-2.png
  doc/images/osi-traffic-participant-use-case-3.png
  doc/open-simulation-interface_user_guide.adoc
  doc/usecases/modeling_traffic_participant.adoc
  local_build_tools/compose.yml
  osi_common.proto
  osi_motionrequest.proto
  osi_object.proto
  setup.py
Labels: FeatureRequest, Documentation, TrafficParticipants, ReadyToMerge

#678 Build: Create a release pipeline that replaces the manual creation of a deliverable package
  .github/workflows/release.yml
Labels: Quality
