Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2023-06, with the labels that each got.

#721 Fix sensordata reference frame definitions
  osi_detectedlane.proto
  osi_detectedobject.proto
  osi_detectedroadmarking.proto
  osi_detectedtrafficlight.proto
  osi_detectedtrafficsign.proto
  osi_featuredata.proto
  osi_logicaldetectiondata.proto
  osi_sensorview.proto
Labels: Bug, HelpWanted, Documentation, Harmonisation, ReadyToMerge

#723 Fix documentation on coordinate systems and transformations
  doc/architecture/reference_points_coordinate_systems.adoc
  doc/images/OSI_MovingObject.svg
  doc/images/osi_example_coordinate_systems.png
  doc/images/osi_example_coordinate_systems.svg
  doc/usecases/transforming_coordinate_systems.adoc
  osi_object.proto
Labels: HelpWanted, Harmonisation, ReadyToMerge

#731 Move missing vcpkg information to prerequisites
  doc/setup/installing_prerequisites.adoc
  doc/setup/installing_windows_cpp.adoc
Labels: Documentation, ReadyToMerge

#729 Added radial_velocity to LidarDetection
  osi_featuredata.proto
Labels: ReadyToMerge

#718 Streaming Interface
  CMakeLists.txt
  doc/architecture/architecture_overview.adoc
  doc/architecture/streaming_update.adoc
  doc/images/osi-streaming-principle.PNG
  doc/open-simulation-interface_user_guide.adoc
  osi_streamingupdate.proto
  setup.py
Labels: ReadyToMerge

#710 Draft for discussion: Add detailed pedestrian description to MovingObject
  doc/images/OSI_PedestrianModelHierarchy.jpg
  doc/images/OSI_SkeletonNamingConvention.svg
  osi_object.proto
Labels: Concept, ReadyToMerge, Other Models, OpenMSL
