Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2024-05, with the labels that each got.

#801 Fix osi trace robustness
  osi3trace/osi_trace.py
  tests/test_osi_trace.py
Labels: Bug, ReadyToMerge

#790 Improve omit_static_information field description
  osi_sensorviewconfiguration.proto
Labels: Bug, ReadyToMerge

#800 Update and harmonize python installation instructions
  doc/setup/installing_linux_python.adoc
  doc/setup/installing_windows_python.adoc
Labels: Bug, ReadyToMerge

#803 Fix outdated documentation on formatting scripts
  doc/architecture/formatting_script.adoc
  doc/open-simulation-interface_user_guide.adoc
Labels: Bug, ReadyToMerge

#806 Add rules according to notes in the documentation
  osi_common.proto
  osi_detectedobject.proto
  osi_trafficcommand.proto
Labels: ReadyToMerge

#802 Add full release publication of python packages
  .github/workflows/protobuf.yml
Labels: Quality, ReadyToMerge

#813 Clarify handling of purely technical IDs
  osi_common.proto
  osi_sensorview.proto
  rules.yml
Labels: Bug, ReadyToMerge

#810 Added hvd as a trace file type for HostVehicleData
  doc/architecture/trace_file_naming.adoc
Labels: ReadyToMerge

#814 Adjust minimum protobuf requirement (fix #807)
  doc/setup/installing_prerequisites.adoc
Labels: Bug, ReadyToMerge
