Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2024-02, with the labels that each got.

#705 feat: New OSI message osi_route
  CMakeLists.txt
  doc/images/OSI_Planned_Route.png
  doc/images/OSI_Route_Segment.png
  osi_hostvehicledata.proto
  osi_route.proto
  setup.py
Labels: ReadyToMerge, Other Models

#769 Add orientation rate to PedestrianAttributes::Bone
  osi_object.proto
Labels: ReadyForCCBReview

#777 Removal of the historical .txt trace file format and related scripts
  doc/architecture/formatting_scripts.adoc
  doc/architecture/trace_file_formats.adoc
  format/OSITrace.py
  format/osi2read.py
  format/txt2osi.py
Labels: Documentation, ReadyToMerge
