Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2024-04, with the labels that each got.

#795 Add pyspelling html filter
  .github/.pyspelling.yml
  .github/spelling_custom_words_en_US.txt
Labels: Quality, ReadyToMerge

#787 Deprecate various car types in favor of new alias TYPE_CAR
  osi_object.proto
Labels: Harmonisation, ReadyToMerge

#767 Fix streaming principle image reference
  doc/images/osi-streaming-principle.png
Labels: Bug, Documentation, ReadyToMerge

#753 Logical Traffic Rules and Speed Limit
  osi_logicallane.proto
Labels: ReadyToMerge
