Repository OpenSimulationInterface/open-simulation-interface, pull requests merged in 2024-03, with the labels that each got.

#774 Fix typos in proto files
  .github/.pyspelling.yml
  .github/spelling_custom_words_en_US.txt
  .github/workflows/protobuf.yml
  osi_common.proto
  osi_detectedobject.proto
  osi_environment.proto
  osi_featuredata.proto
  osi_hostvehicledata.proto
  osi_lane.proto
  osi_logicaldetectiondata.proto
  osi_logicallane.proto
  osi_object.proto
  osi_referenceline.proto
  osi_roadmarking.proto
  osi_sensorview.proto
  osi_sensorviewconfiguration.proto
  osi_streamingupdate.proto
  osi_trafficcommand.proto
  osi_trafficlight.proto
  osi_trafficsign.proto
  osi_trafficupdate.proto
  tests/test_invalid_enum.py
Labels: ReadyForCCBReview

#732 Add new message for sub-bounding boxes
  osi_common.proto
Labels: ReadyToMerge, Other Models

#759 Update github actions for release workflow
  .github/workflows/antora-generator.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
Labels: Quality

#746 Add check that all proto files are included in build
  .github/workflows/protobuf.yml
Labels: Quality

#781 feat: Add virtual detection area
  osi_common.proto
  osi_sensordata.proto
Labels: ReadyToMerge

#783 Modernize python build setup, protoc dependency
  .github/workflows/protobuf.yml
  .gitignore
  MANIFEST.in
  format/OSITrace.py
  osi3trace/osi2read.py
  osi3trace/osi_trace.py
  pyproject.toml
  requirements_tests.txt
  setup.py
  tests/test_osi_trace.py
Labels: Quality, ReadyToMerge

#788 Remove OSC todo comment from source_reference
  osi_object.proto
Labels: Documentation, Quality, ReadyToMerge

#792 Fix documentation on FeatureData messages
  doc/architecture/architecture_overview.adoc
  doc/architecture/feature_data.adoc
  doc/architecture/sensor_data.adoc
  doc/open-simulation-interface_user_guide.adoc
Labels: Documentation, Quality, ReadyToMerge

#794 Feature/proj offset
  .github/spelling_custom_words_en_US.txt
  doc/architecture/reference_points_coordinate_systems.adoc
  osi_groundtruth.proto
Labels: Harmonisation, ReadyToMerge
